unit unitLogoMaker;

interface

  procedure GetAndAddLogomarca(PrintStrategy: string);


implementation

uses
  Classes, SysUtils;

procedure GetAndAddLogomarca(PrintStrategy: string);

var
   ARCHIEVE_ORIGINAL_ETIQUETA: textFile;
   ARCHIEVE_LOGOMARCAS: textFile;
   ARCHIEVE_NEW_ETIQUETA: textFile;

   ARRAY_ORIGINAL_ETIQUETA: array[1..500] of AnsiString;
   ARRAY_LOGOMARCAS: array[1..500] of AnsiString;
   ARRAY_NEW_ETIQUETA: array[1..500] of AnsiString;

   CURRENT_INDEX_ORIGINAL_ETIUETA: integer;
   CURRENT_INDEX_LOGOMARCAS: integer;
   CURRENT_INDEX_NEW_ETIQUETA: integer;

   AUX_INDEX: integer;

   NUM_LINES_ORIGINAL_ETIQUETA_FILE: integer;
   NUM_LINES_LOGOMARCAS_FILE: integer;
   NUM_LINES_NEW_ETIQUETA_FILE: integer;

   QUANTITY_N_COMMAND: integer;
   REPOSITION_N_COMMAND: integer;

   COUNTER: integer;

begin
  CURRENT_INDEX_ORIGINAL_ETIUETA:= 1;
  CURRENT_INDEX_LOGOMARCAS:= 1;

  NUM_LINES_ORIGINAL_ETIQUETA_FILE:= 0;
  NUM_LINES_LOGOMARCAS_FILE:= 0;
  NUM_LINES_NEW_ETIQUETA_FILE:= 0;

  QUANTITY_N_COMMAND:= 0;

  if (PrintStrategy = 'ONE') then
  begin
     assignFile(ARCHIEVE_LOGOMARCAS, 'ONE_LOGOMARCA.binnary');
     REPOSITION_N_COMMAND:=1;
  end;

  if (PrintStrategy = 'TWO') then
  begin
     assignFile(ARCHIEVE_LOGOMARCAS, 'TWO_LOGOMARCA.binnary');
     REPOSITION_N_COMMAND:=1;
  end;

  if (PrintStrategy = 'THREE') then
  begin
     assignFile(ARCHIEVE_LOGOMARCAS, 'THREE_LOGOMARCA.binnary');
     REPOSITION_N_COMMAND:=3;
  end;

  reset(ARCHIEVE_LOGOMARCAS);

  while (not EOF(ARCHIEVE_LOGOMARCAS)) do
  begin
   readln(ARCHIEVE_LOGOMARCAS, ARRAY_LOGOMARCAS[CURRENT_INDEX_LOGOMARCAS]);

   CURRENT_INDEX_LOGOMARCAS:= CURRENT_INDEX_LOGOMARCAS + 1;
   NUM_LINES_LOGOMARCAS_FILE:= NUM_LINES_LOGOMARCAS_FILE + 1;
   NUM_LINES_NEW_ETIQUETA_FILE:= NUM_LINES_NEW_ETIQUETA_FILE + 1;
  end;

  close(ARCHIEVE_LOGOMARCAS);

  assignFile(ARCHIEVE_ORIGINAL_ETIQUETA, 'etiqueta.txt');
  assignFile(ARCHIEVE_NEW_ETIQUETA, 'etiqueta.txt');

  reset(ARCHIEVE_ORIGINAL_ETIQUETA);

  while(not EOF(ARCHIEVE_ORIGINAL_ETIQUETA)) do
  begin
    readln(ARCHIEVE_ORIGINAL_ETIQUETA, ARRAY_ORIGINAL_ETIQUETA[CURRENT_INDEX_ORIGINAL_ETIUETA]);

    if (ARRAY_ORIGINAL_ETIQUETA[CURRENT_INDEX_ORIGINAL_ETIUETA] = 'N') then
    begin
    	QUANTITY_N_COMMAND:= QUANTITY_N_COMMAND + 1;
    end;

    CURRENT_INDEX_ORIGINAL_ETIUETA:= CURRENT_INDEX_ORIGINAL_ETIUETA + 1;
    NUM_LINES_ORIGINAL_ETIQUETA_FILE:= NUM_LINES_ORIGINAL_ETIQUETA_FILE + 1;

  end;

  close(ARCHIEVE_ORIGINAL_ETIQUETA);

  NUM_LINES_NEW_ETIQUETA_FILE:= NUM_LINES_ORIGINAL_ETIQUETA_FILE + (REPOSITION_N_COMMAND * QUANTITY_N_COMMAND);

  CURRENT_INDEX_ORIGINAL_ETIUETA:= 1;
  CURRENT_INDEX_NEW_ETIQUETA:= 1;

  for COUNTER:=1 to NUM_LINES_NEW_ETIQUETA_FILE do
  begin
      if (ARRAY_ORIGINAL_ETIQUETA[CURRENT_INDEX_ORIGINAL_ETIUETA] <> 'N') then
      begin

         ARRAY_NEW_ETIQUETA[CURRENT_INDEX_NEW_ETIQUETA]:= ARRAY_ORIGINAL_ETIQUETA[CURRENT_INDEX_ORIGINAL_ETIUETA];
         CURRENT_INDEX_ORIGINAL_ETIUETA:= CURRENT_INDEX_ORIGINAL_ETIUETA + 1;

         CURRENT_INDEX_NEW_ETIQUETA:=CURRENT_INDEX_NEW_ETIQUETA+1;
      end else
      begin
         for CURRENT_INDEX_LOGOMARCAS:=1 to NUM_LINES_LOGOMARCAS_FILE do
         begin

           ARRAY_NEW_ETIQUETA[CURRENT_INDEX_NEW_ETIQUETA]:= ARRAY_LOGOMARCAS[CURRENT_INDEX_LOGOMARCAS];
           CURRENT_INDEX_NEW_ETIQUETA:=CURRENT_INDEX_NEW_ETIQUETA + 1;

         end;

         ARRAY_NEW_ETIQUETA[CURRENT_INDEX_NEW_ETIQUETA - REPOSITION_N_COMMAND - 1]:= 'N';

         CURRENT_INDEX_ORIGINAL_ETIUETA:= CURRENT_INDEX_ORIGINAL_ETIUETA + 1;
      end;
  end;


  rewrite(ARCHIEVE_NEW_ETIQUETA);

  for AUX_INDEX:=1 to NUM_LINES_NEW_ETIQUETA_FILE do
  begin
    writeln(ARCHIEVE_NEW_ETIQUETA, ARRAY_NEW_ETIQUETA[AUX_INDEX]);
  end;

  close(ARCHIEVE_NEW_ETIQUETA);
end;

end.

