unit Prevenda.Constants.GondolaG003;

interface

const
  DESCRIPTION_X_DEFAULT = 54;
  DESCRIPTION_Y_DEFAULT = 8;

  UNITY_X_DEFAULT = 54;
  UNITY_Y_DEFAULT = 63;

  PRICE_VAREJO_LABEL_X_DEFAULT = 190;
  PRICE_VAREJO_LABEL_Y_DEFAULT = 88;
  PRICE_VAREJO_VALUE_X_DEFAULT = 130;
  PRICE_VAREJO_VALUE_Y_DEFAULT = 120;

  PRICE_ATACADO_LABEL_X_DEFAULT = 526;
  PRICE_ATACADO_LABEL_Y_DEFAULT = 88;
  PRICE_ATACADO_VALUE_X_DEFAULT = 466;
  PRICE_ATACADO_VALUE_Y_DEFAULT = 120;

implementation

end.
