unit Prevenda.Constants.GondolaAtacadoVarejo001;

interface

const
  DESCRIPTION_X_DEFAULT = 54;
  DESCRIPTION_Y_DEFAULT = 8;

  UNITY_X_DEFAULT = 54;
  UNITY_Y_DEFAULT = 63;

  SINGLE_PRICE_LABEL_X_DEFAULT = 334;
  SINGLE_PRICE_LABEL_Y_DEFAULT = 88;
  SINGLE_PRICE_VALUE_X_DEFAULT = 274;
  SINGLE_PRICE_VALUE_Y_DEFAULT = 120;

  DOUBLE_PRICE_VAREJO_LABEL_X_DEFAULT = 190;
  DOUBLE_PRICE_VAREJO_LABEL_Y_DEFAULT = 88;
  DOUBLE_PRICE_VAREJO_VALUE_X_DEFAULT = 130;
  DOUBLE_PRICE_VAREJO_VALUE_Y_DEFAULT = 120;

  PRICE_ATACADO_LABEL_X_DEFAULT = 526;
  PRICE_ATACADO_LABEL_Y_DEFAULT = 88;
  PRICE_ATACADO_VALUE_X_DEFAULT = 466;
  PRICE_ATACADO_VALUE_Y_DEFAULT = 120;

implementation

end.
