unit Prevenda.Constants.GondolaG001;

interface

const
  DESCRIPTION_X_DEFAULT = 16;
  DESCRIPTION_Y_DEFAULT = 8;

  UNITY_X_DEFAULT = 16;
  UNITY_Y_DEFAULT = 60;

  BARCODE_SYMBOL_X_DEFAULT = 24;
  BARCODE_SYMBOL_Y_DEFAULT = 114;
  BARCODE_VALUE_X_DEFAULT = 120;
  BARCODE_VALUE_Y_DEFAULT = 168;

  PRICE_SYMBOL_X_DEFAULT = 450;
  PRICE_SYMBOL_Y_DEFAULT = 128;
  PRICE_VALUE_X_DEFAULT = 498;
  PRICE_VALUE_Y_DEFAULT = 80;

implementation

end.
