unit Prevenda.Constants.GondolaG002;

interface

const
  DESCRIPTION_X_DEFAULT = 54;
  DESCRIPTION_Y_DEFAULT = 31;

  UNITY_X_DEFAULT = 54;
  UNITY_Y_DEFAULT = 63;

  PRICE_LABEL_X_DEFAULT = 350;
  PRICE_LABEL_Y_DEFAULT = 85;
  PRICE_VALUE_X_DEFAULT = 256;
  PRICE_VALUE_Y_DEFAULT = 120;

implementation

end.
